{% set name = "opentelemetry-instrumentation" %}
{% set version = "0.36b0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opentelemetry_instrumentation-{{ version }}.tar.gz
  sha256: e3ddac9b3b93408ef26c8ecbf38f717042977e16381bb4cd329a5b4cf16998cf

build:
  entry_points:
    - opentelemetry-bootstrap = opentelemetry.instrumentation.bootstrap:run
    - opentelemetry-instrument = opentelemetry.instrumentation.auto_instrumentation:run
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - hatchling
    - pip
  run:
    - python >=3.7
    - opentelemetry-api >=1.4,<2.dev0
    - setuptools >=16.0
    - wrapt >=1.0.0,<2.0.0

test:
  imports:
    - opentelemetry.instrumentation
  commands:
    - pip check
    - opentelemetry-bootstrap --help
    - opentelemetry-instrument --help
  requires:
    - pip

about:
  summary: Instrumentation Tools & Auto Instrumentation for OpenTelemetry Python
  license: Apache-2.0
  license_file: LICENSE

extra:
  anaconda-services:
    ref: https://anaconda.zendesk.com/agent/tickets/70829
    reason: Dependency for chromadb
  recipe-maintainers:
    - ianaobi
                                                                              

