{% set name = "opentelemetry-instrumentation" %}
{% set version = "0.47b0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opentelemetry_instrumentation-{{ version }}.tar.gz
  sha256: 96f9885e450c35e3f16a4f33145f2ebf620aea910c9fd74a392bbc0f807a350f

build:
  number: 0
  skip: True  # [py<38]
  entry_points:
    - opentelemetry-instrument = opentelemetry.instrumentation.auto_instrumentation:run
    - opentelemetry-bootstrap = opentelemetry.instrumentation.bootstrap:run
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python
    - hatchling
  run:
    - python
    - opentelemetry-api >=1.4,<2.dev0
    - setuptools >=16.0
    - wrapt >=1.0.0, <2.0.0

test:
  imports:
    - opentelemetry.instrumentation
  commands:
    - pip check
    - opentelemetry-instrument --help
    - opentelemetry-bootstrap --help
  requires:
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python
  summary: Instrumentation Tools & Auto Instrumentation for OpenTelemetry Python
  license_family: APACHE
  license: Apache-2.0
  license_file: LICENSE.txt
  description: |
    OpenTelemetry Instrumentation provides tools and auto-instrumentation for OpenTelemetry Python.
    This package is intended to be used in conjunction with the OpenTelemetry SDK.
  dev_url: https://github.com/open-telemetry/opentelemetry-python
  doc_url: https://opentelemetry.io/docs/getting-started/dev/

extra:
  recipe-maintainers:
    - twoodwark
    - mariusvniekerk
