{% set name = "opentelemetry-instrumentation" %}
{% set version = "0.58b0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_')}}-{{ version }}.tar.gz
  sha256: df640f3ac715a3e05af145c18f527f4422c6ab6c467e40bd24d2ad75a00cb705

build:
  number: 0
  entry_points:
    - opentelemetry-instrument = opentelemetry.instrumentation.auto_instrumentation:run
    - opentelemetry-bootstrap = opentelemetry.instrumentation.bootstrap:run
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: True  # [py<39]

requirements:
  host:
    - pip
    - python 
    - hatchling
  run:
    - python
    - opentelemetry-api ~=1.4
    - opentelemetry-semantic-conventions 0.58b0
    - wrapt >=1.0.0,< 2.0.0
    - packaging >=18.0

# Unable to run the tests, opentelemetry-test-utils is not in the main channel. No module named 'opentelemetry.test'.
test:
  imports:
    - opentelemetry.instrumentation
  commands:
    - pip check
    - opentelemetry-instrument --help
    - opentelemetry-bootstrap --help
  requires:
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python
  summary: Instrumentation Tools & Auto Instrumentation for OpenTelemetry Python
  license_family: APACHE
  license: Apache-2.0
  license_file: LICENSE.txt
  description: |
    OpenTelemetry Instrumentation provides tools and auto-instrumentation for OpenTelemetry Python.
    This package is intended to be used in conjunction with the OpenTelemetry SDK.
  dev_url: https://github.com/open-telemetry/opentelemetry-python
  doc_url: https://opentelemetry.io/docs/getting-started/dev/

extra:
  recipe-maintainers:
    - rxm7706
    - twoodwark
    - mariusvniekerk